# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-25 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chris_Blog', '0002_auto_20170125_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
    ]
