# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Chris_Blog', '0003_remove_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=datetime.datetime(2017, 1, 26, 18, 18, 22, 978000, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
